apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9-community
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://sonarqube-db:5432/sonar
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonar-db-credentials
              key: POSTGRES_USER
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonar-db-credentials
              key: POSTGRES_PASSWORD
        - name: SONAR_JDBC_MAXACTIVE
          value: "50"
        - name: SONAR_JDBC_MAXIDLE
          value: "5"
        - name: SONAR_JDBC_MINIDLE
          value: "2"
        - name: SONAR_JDBC_MAXWAIT
          value: "5000"
        - name: SONAR_JDBC_MAXLIFETIME
          value: "1800000"
        - name: SONAR_WEB_JAVAOPTS
          value: "-Xmx2g -Xms1g -XX:+HeapDumpOnOutOfMemoryError"
        - name: SONAR_CE_JAVAOPTS
          value: "-Xmx2g -Xms1g -XX:+HeapDumpOnOutOfMemoryError"
        resources:
          limits:
            cpu: "4"
            memory: "10Gi"
          requests:
            cpu: "2"
            memory: "6Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 5